# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.1.1
_src_path: gh:radio-aktywne/template-app-next
accountname: radio-aktywne
appname: webfuse
description: Audio streaming with Liquidsoap web UI 🧼
docs: true
docsurl: https://radio-aktywne.github.io/app-webfuse
envprefix: WEBFUSE
imagename: apps/webfuse
keyprefix: webfuse
port: 12000
registry: true
releases: true
reponame: app-webfuse
repourl: https://github.com/radio-aktywne/app-webfuse
