services:
  webfuse:
    build:
      context: ./
      network: host
    environment:
      - "WEBFUSE__SERVER__HOST=${WEBFUSE__SERVER__HOST:-0.0.0.0}"
      - "WEBFUSE__SERVER__PORT=${WEBFUSE__SERVER__PORT:-12000}"
      - "WEBFUSE__EMIFUSE__HTTP__SCHEME=${WEBFUSE__EMIFUSE__HTTP__SCHEME:-http}"
      - "WEBFUSE__EMIFUSE__HTTP__HOST=${WEBFUSE__EMIFUSE__HTTP__HOST:-localhost}"
      - "WEBFUSE__EMIFUSE__HTTP__PORT=${WEBFUSE__EMIFUSE__HTTP__PORT:-9001}"
      - "WEBFUSE__EMIFUSE__HTTP__PATH=${WEBFUSE__EMIFUSE__HTTP__PATH:-}"
      - "WEBFUSE__EMITUNES__HTTP__SCHEME=${WEBFUSE__EMITUNES__HTTP__SCHEME:-http}"
      - "WEBFUSE__EMITUNES__HTTP__HOST=${WEBFUSE__EMITUNES__HTTP__HOST:-localhost}"
      - "WEBFUSE__EMITUNES__HTTP__PORT=${WEBFUSE__EMITUNES__HTTP__PORT:-42000}"
      - "WEBFUSE__EMITUNES__HTTP__PATH=${WEBFUSE__EMITUNES__HTTP__PATH:-}"
    network_mode: host
